"""Initial migration - create all tables

Revision ID: 331b479b9160
Revises: 
Create Date: 2025-12-01 12:26:21.209711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331b479b9160'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create departments table WITHOUT foreign key constraint to avoid circular dependency
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_observed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date', 'market', name='uq_holiday_date_market')
    )
    op.create_index(op.f('ix_market_holidays_holiday_date'), 'market_holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_market_holidays_id'), 'market_holidays', ['id'], unique=False)
    op.create_index(op.f('ix_market_holidays_market'), 'market_holidays', ['market'], unique=False)
    op.create_index(op.f('ix_market_holidays_year'), 'market_holidays', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pto_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vacation_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_pending', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sick_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sick_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('personal_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('personal_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remote_weekly_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', name='uq_user_year')
    )
    op.create_index(op.f('ix_pto_balances_id'), 'pto_balances', ['id'], unique=False)
    op.create_index(op.f('ix_pto_balances_user_id'), 'pto_balances', ['user_id'], unique=False)
    op.create_index(op.f('ix_pto_balances_year'), 'pto_balances', ['year'], unique=False)
    op.create_table('pto_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('pto_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pto_requests_end_date'), 'pto_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_pto_requests_id'), 'pto_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pto_requests_pto_type'), 'pto_requests', ['pto_type'], unique=False)
    op.create_index(op.f('ix_pto_requests_start_date'), 'pto_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_pto_requests_status'), 'pto_requests', ['status'], unique=False)
    op.create_index(op.f('ix_pto_requests_user_id'), 'pto_requests', ['user_id'], unique=False)
    
    # Add the foreign key constraint for departments.manager_id after users table is created
    op.create_foreign_key('fk_departments_manager_id', 'departments', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint first
    op.drop_constraint('fk_departments_manager_id', 'departments', type_='foreignkey')
    
    op.drop_index(op.f('ix_pto_requests_user_id'), table_name='pto_requests')
    op.drop_index(op.f('ix_pto_requests_status'), table_name='pto_requests')
    op.drop_index(op.f('ix_pto_requests_start_date'), table_name='pto_requests')
    op.drop_index(op.f('ix_pto_requests_pto_type'), table_name='pto_requests')
    op.drop_index(op.f('ix_pto_requests_id'), table_name='pto_requests')
    op.drop_index(op.f('ix_pto_requests_end_date'), table_name='pto_requests')
    op.drop_table('pto_requests')
    op.drop_index(op.f('ix_pto_balances_year'), table_name='pto_balances')
    op.drop_index(op.f('ix_pto_balances_user_id'), table_name='pto_balances')
    op.drop_index(op.f('ix_pto_balances_id'), table_name='pto_balances')
    op.drop_table('pto_balances')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_holidays_year'), table_name='market_holidays')
    op.drop_index(op.f('ix_market_holidays_market'), table_name='market_holidays')
    op.drop_index(op.f('ix_market_holidays_id'), table_name='market_holidays')
    op.drop_index(op.f('ix_market_holidays_holiday_date'), table_name='market_holidays')
    op.drop_table('market_holidays')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
