"""Add location fields and new leave tables

Revision ID: 45980e200e7b
Revises: c8bc1c49c679
Create Date: 2025-12-04 19:05:30.973942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45980e200e7b'
down_revision: Union[str, None] = 'c8bc1c49c679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='System code: VACATION, SICK, PERSONAL, BEREAVEMENT, FMLA, JURY_DUTY'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False, comment='accrued, allocated, tracking_only'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('requires_documentation', sa.Boolean(), nullable=False, comment='True for bereavement, fmla, jury_duty'),
    sa.Column('deducts_from_balance', sa.Boolean(), nullable=False, comment='False for jury_duty, bereavement, fmla'),
    sa.Column('is_paid', sa.Boolean(), nullable=False, comment='Default paid status for this leave type'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Display order in dropdowns'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_leave_types_id'), 'leave_types', ['id'], unique=False)
    op.create_table('vacation_accrual_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_years_service', sa.Integer(), nullable=False, comment='Minimum years (inclusive)'),
    sa.Column('max_years_service', sa.Integer(), nullable=True, comment='Maximum years (inclusive), NULL = no upper limit'),
    sa.Column('annual_days', sa.Numeric(precision=4, scale=2), nullable=False, comment='Total vacation days granted per year'),
    sa.Column('monthly_accrual_rate', sa.Numeric(precision=4, scale=2), nullable=False, comment='Days accrued per month (annual_days / 12)'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_accrual_tiers_id'), 'vacation_accrual_tiers', ['id'], unique=False)
    op.create_table('carryover_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('from_year', sa.Integer(), nullable=False, comment='Year the hours are coming from'),
    sa.Column('to_year', sa.Integer(), nullable=False, comment='Year the hours are carrying into'),
    sa.Column('hours_requested', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hours_approved', sa.Numeric(precision=5, scale=2), nullable=True, comment='May differ from requested'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, approved, denied'),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('employee_notes', sa.Text(), nullable=True, comment='Reason for carryover request'),
    sa.Column('manager_notes', sa.Text(), nullable=True, comment='Approval/denial notes'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carryover_requests_employee_id'), 'carryover_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_carryover_requests_id'), 'carryover_requests', ['id'], unique=False)
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('location_state', sa.String(length=2), nullable=True, comment='State code or NULL for default'),
    sa.Column('location_city', sa.String(length=50), nullable=True, comment='City name or NULL for state-wide'),
    sa.Column('accrual_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Hours accrued per period'),
    sa.Column('accrual_period', sa.String(length=20), nullable=True, comment='monthly, per_hours_worked'),
    sa.Column('accrual_hours_divisor', sa.Integer(), nullable=True, comment='For per_hours_worked: 40, 35, or 30'),
    sa.Column('max_annual_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Maximum hours that can be accrued per year'),
    sa.Column('max_carryover_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Maximum hours that can roll over'),
    sa.Column('waiting_period_days', sa.Integer(), nullable=False, comment='Days before leave can be used (e.g., 90 for probation)'),
    sa.Column('min_increment_hours', sa.Numeric(precision=4, scale=2), nullable=True, comment='Minimum request size (e.g., 2.0 or 4.0 hours)'),
    sa.Column('max_increment_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Maximum single request (NULL = unlimited)'),
    sa.Column('advance_notice_days', sa.Integer(), nullable=False, comment='Required advance notice (e.g., 14 days for vacation)'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='NULL = currently active'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_policies_id'), 'leave_policies', ['id'], unique=False)
    op.create_index(op.f('ix_leave_policies_leave_type_id'), 'leave_policies', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_policies_location_state'), 'leave_policies', ['location_state'], unique=False)
    op.add_column('users', sa.Column('location_state', sa.String(length=2), nullable=True, comment='State code: IL, NY, CT, FL'))
    op.add_column('users', sa.Column('location_city', sa.String(length=50), nullable=True, comment='City name (e.g., Chicago for IL-specific rules)'))
    op.create_index(op.f('ix_users_location_state'), 'users', ['location_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_location_state'), table_name='users')
    op.drop_column('users', 'location_city')
    op.drop_column('users', 'location_state')
    op.drop_index(op.f('ix_leave_policies_location_state'), table_name='leave_policies')
    op.drop_index(op.f('ix_leave_policies_leave_type_id'), table_name='leave_policies')
    op.drop_index(op.f('ix_leave_policies_id'), table_name='leave_policies')
    op.drop_table('leave_policies')
    op.drop_index(op.f('ix_carryover_requests_id'), table_name='carryover_requests')
    op.drop_index(op.f('ix_carryover_requests_employee_id'), table_name='carryover_requests')
    op.drop_table('carryover_requests')
    op.drop_index(op.f('ix_vacation_accrual_tiers_id'), table_name='vacation_accrual_tiers')
    op.drop_table('vacation_accrual_tiers')
    op.drop_index(op.f('ix_leave_types_id'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
