"""Add carryover fields to pto_balances

Revision ID: 54c0c9e52ce9
Revises: 45980e200e7b
Create Date: 2025-12-04 20:38:24.077325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c0c9e52ce9'
down_revision: Union[str, None] = '45980e200e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pto_balances', sa.Column('vacation_carryover', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00', comment='Vacation hours carried over from previous year'))
    op.add_column('pto_balances', sa.Column('sick_carryover', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00', comment='Sick hours carried over from previous year'))
    op.add_column('pto_balances', sa.Column('personal_carryover', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00', comment='Personal hours carried over from previous year'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pto_balances', 'personal_carryover')
    op.drop_column('pto_balances', 'sick_carryover')
    op.drop_column('pto_balances', 'vacation_carryover')
    # ### end Alembic commands ###
