"""Add anniversary_date, remote_schedule to users and is_paid to pto_requests

Revision ID: c8bc1c49c679
Revises: 331b479b9160
Create Date: 2025-12-03 16:27:24.037336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bc1c49c679'
down_revision: Union[str, None] = '331b479b9160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pto_requests', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('anniversary_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('remote_schedule', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remote_schedule')
    op.drop_column('users', 'anniversary_date')
    op.drop_column('pto_requests', 'is_paid')
    # ### end Alembic commands ###
