"""initial_sqlite_migration

Revision ID: d1d45e7991f9
Revises: 
Create Date: 2025-12-06 18:59:18.109470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d45e7991f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='System code: VACATION, SICK, PERSONAL, BEREAVEMENT, FMLA, JURY_DUTY'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False, comment='accrued, allocated, tracking_only'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('requires_documentation', sa.Boolean(), nullable=False, comment='True for bereavement, fmla, jury_duty'),
    sa.Column('deducts_from_balance', sa.Boolean(), nullable=False, comment='False for jury_duty, bereavement, fmla'),
    sa.Column('is_paid', sa.Boolean(), nullable=False, comment='Default paid status for this leave type'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Display order in dropdowns'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_types_id'), ['id'], unique=False)

    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_observed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date', 'market', name='uq_holiday_date_market')
    )
    with op.batch_alter_table('market_holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_holidays_holiday_date'), ['holiday_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holidays_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holidays_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_holidays_year'), ['year'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('anniversary_date', sa.Date(), nullable=True),
    sa.Column('remote_schedule', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('location_state', sa.String(length=2), nullable=True, comment='State code: IL, NY, CT, FL'),
    sa.Column('location_city', sa.String(length=50), nullable=True, comment='City name (e.g., Chicago for IL-specific rules)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_location_state'), ['location_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vacation_accrual_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_years_service', sa.Integer(), nullable=False, comment='Minimum years (inclusive)'),
    sa.Column('max_years_service', sa.Integer(), nullable=True, comment='Maximum years (inclusive), NULL = no upper limit'),
    sa.Column('annual_days', sa.Numeric(precision=4, scale=2), nullable=False, comment='Total vacation days granted per year'),
    sa.Column('monthly_accrual_rate', sa.Numeric(precision=4, scale=2), nullable=False, comment='Days accrued per month (annual_days / 12)'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacation_accrual_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacation_accrual_tiers_id'), ['id'], unique=False)

    op.create_table('carryover_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('from_year', sa.Integer(), nullable=False, comment='Year the hours are coming from'),
    sa.Column('to_year', sa.Integer(), nullable=False, comment='Year the hours are carrying into'),
    sa.Column('hours_requested', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hours_approved', sa.Numeric(precision=5, scale=2), nullable=True, comment='May differ from requested'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, approved, denied'),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('employee_notes', sa.Text(), nullable=True, comment='Reason for carryover request'),
    sa.Column('manager_notes', sa.Text(), nullable=True, comment='Approval/denial notes'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carryover_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carryover_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carryover_requests_id'), ['id'], unique=False)

    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('location_state', sa.String(length=2), nullable=True, comment='State code or NULL for default'),
    sa.Column('location_city', sa.String(length=50), nullable=True, comment='City name or NULL for state-wide'),
    sa.Column('accrual_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Hours accrued per period'),
    sa.Column('accrual_period', sa.String(length=20), nullable=True, comment='monthly, per_hours_worked'),
    sa.Column('accrual_hours_divisor', sa.Integer(), nullable=True, comment='For per_hours_worked: 40, 35, or 30'),
    sa.Column('max_annual_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Maximum hours that can be accrued per year'),
    sa.Column('max_carryover_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Maximum hours that can roll over'),
    sa.Column('waiting_period_days', sa.Integer(), nullable=False, comment='Days before leave can be used (e.g., 90 for probation)'),
    sa.Column('min_increment_hours', sa.Numeric(precision=4, scale=2), nullable=True, comment='Minimum request size (e.g., 2.0 or 4.0 hours)'),
    sa.Column('max_increment_hours', sa.Numeric(precision=5, scale=2), nullable=True, comment='Maximum single request (NULL = unlimited)'),
    sa.Column('advance_notice_days', sa.Integer(), nullable=False, comment='Required advance notice (e.g., 14 days for vacation)'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='NULL = currently active'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_policies_leave_type_id'), ['leave_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_policies_location_state'), ['location_state'], unique=False)

    op.create_table('pto_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vacation_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_pending', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sick_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sick_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('personal_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('personal_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_carryover', sa.Numeric(precision=5, scale=2), nullable=False, comment='Vacation hours carried over from previous year'),
    sa.Column('sick_carryover', sa.Numeric(precision=5, scale=2), nullable=False, comment='Sick hours carried over from previous year'),
    sa.Column('personal_carryover', sa.Numeric(precision=5, scale=2), nullable=False, comment='Personal hours carried over from previous year'),
    sa.Column('remote_weekly_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', name='uq_user_year')
    )
    with op.batch_alter_table('pto_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pto_balances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_balances_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_balances_year'), ['year'], unique=False)

    op.create_table('pto_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('pto_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pto_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pto_requests_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_pto_type'), ['pto_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pto_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pto_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pto_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_status'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_start_date'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_pto_type'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_id'))
        batch_op.drop_index(batch_op.f('ix_pto_requests_end_date'))

    op.drop_table('pto_requests')
    with op.batch_alter_table('pto_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pto_balances_year'))
        batch_op.drop_index(batch_op.f('ix_pto_balances_user_id'))
        batch_op.drop_index(batch_op.f('ix_pto_balances_id'))

    op.drop_table('pto_balances')
    with op.batch_alter_table('leave_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_policies_location_state'))
        batch_op.drop_index(batch_op.f('ix_leave_policies_leave_type_id'))
        batch_op.drop_index(batch_op.f('ix_leave_policies_id'))

    op.drop_table('leave_policies')
    with op.batch_alter_table('carryover_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carryover_requests_id'))
        batch_op.drop_index(batch_op.f('ix_carryover_requests_employee_id'))

    op.drop_table('carryover_requests')
    with op.batch_alter_table('vacation_accrual_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacation_accrual_tiers_id'))

    op.drop_table('vacation_accrual_tiers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_location_state'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('market_holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_holidays_year'))
        batch_op.drop_index(batch_op.f('ix_market_holidays_market'))
        batch_op.drop_index(batch_op.f('ix_market_holidays_id'))
        batch_op.drop_index(batch_op.f('ix_market_holidays_holiday_date'))

    op.drop_table('market_holidays')
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_types_id'))

    op.drop_table('leave_types')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
